hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.php"
    prefix:   /contao/connect

contao_id_login:
    path: '%contao.backend.route_prefix%/login/contao_id'
    defaults:
        _scope: 'backend'
